database {
  dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
  properties = {
    serverName = ${DB_HOST}
    portNumber = ${DB_PORT}
    databaseName = ${?DB_NAME}
    databaseName = "ecommerce"
    user = ${?DB_USER}
    user = "postgres"
    password = ${?DB_PASSWORD}
    password = "postgres"
  }
  numThreads = 10
  connectionTimeout = 5000
}