database {
  dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
  properties = {
    serverName = ${?DB_HOST}
    serverName = "localhost"
    portNumber = ${?DB_PORT}
    portNumber = "5432"
    databaseName = ${?DB_NAME}
    databaseName = "ecommerce"
    user = ${?DB_USER}
    user = "postgres"
    password = ${?DB_PASSWORD}
    password = "postgres"
  }
  numThreads = 10
  connectionTimeout = 5000
}